run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - .github
    - .vscode

output:
  sort-results: true

linters:
  # Enable all the linters except the ones disabled below
  enable-all: true
  disable:
  # Remove deprecated and deactivated linters
  # - golint
  # - interfacer
  # - ifshort
  # - scopelint
  # - exhaustivestruct
  # - maligned
  # - nosnakecase
  # - varcheck
  # - deadcode
  # - structcheck
  # - gomnd
  # - execinquery
  #
  # Disable deprecated/abandoned linters
  - exportloopref
  # Disable due to test and mock private functions
  - testpackage
  # Disable due to the use of external dependencies
  - depguard
