run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - .github
    - .vscode

output:
  sort-results: true

linters:
  # Enable all the linters except the ones disabled below
  enable-all: true
  disable:
  # Remove dur to deprecated and deactivated
  # - golint
  # - interfacer
  # - ifshort
  # - scopelint
  # - exhaustivestruct
  # - maligned
  # - nosnakecase
  # - varcheck
  # - deadcode
  # - structcheck
  # Disable deprecated/abandoned linters
  - execinquery
  # Disabled due to renaming
  - gomnd
  # Disable due to test and mock private functions
  - testpackage

linters-settings:
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          # Standard library
          - $gostd
          # Required for testing
          - github.com/stretchr/testify
          # Required for real examples
          - github.com/KEINOS/go-todotxt/todo
          # Deprecated but still used
          - github.com/pkg/errors
