# This workflow updates the code coverage of Codecov.
# It runs the unit test and pushes the measured code coverage analysis.
name: "Codecov"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      OS: 'ubuntu-latest'
      GO: '1'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - run: go test -coverprofile coverage.txt ./...

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
